# Generated by Django 4.2.6 on 2023-10-27 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jamcam',
            name='name',
            field=models.CharField(max_length=300, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='capture',
            unique_together={('jam_cam', 'timestamp')},
        ),
    ]
