# Generated by Django 4.2.6 on 2023-10-28 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_capture_num_vehicles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='capture',
            old_name='num_vehicles',
            new_name='vehicle_count',
        ),
        migrations.AddField(
            model_name='capture',
            name='bus_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='capture',
            name='car_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='capture',
            name='motorcycle_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='capture',
            name='truck_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
